version: '3.8'

services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    environment:
      - GOAPP_HOST=goapp
    depends_on:
      - goapp
    ports:
      - "80:80"

  goapp:
    build:
      context: goapp
      dockerfile: Dockerfile
